### ISSUE TITLE
BUG: panic: interface conversion: net.Conn is *nekoutils.mangedFusedConn, not *internet.PacketConnWrapper

### ISSUE THREAD

**Issue by peakedshout** [MatsuriDayo/nekoray#1134]
panic: interface conversion: net.Conn is *nekoutils.mangedFusedConn, not *internet.PacketConnWrapper
goroutine 27 [running]:
github.com/xtls/xray-core/transport/internet/quic.(*clientConnections).openConnection(0x1c009d0, {0x1370d90, 0xc0003db260}, {
0x1368400, 0xc0002880c0}, 0x0?, 0x0?, 0x0?)
	github.com/xtls/xray-core@v1.0.0/transport/internet/quic/dialer.go:151 +0xc13
github.com/xtls/xray-core/transport/internet/quic.Dial(
{0x1370d90, 0xc0003db260}, {{0x1370ff8?, 0xc000391950?}, 0x0?, 0x0?}, 0xc0003cef00)
	github.com/xtls/xray-core@v1.0.0/transport/internet/quic/dialer.go:212 +0x1c5
github.com/xtls/xray-core/transport/internet.Dial({0x1370d90, 0xc0003db260}, {{0x1370ff8?, 0xc000391950?
}, 0x1950?, 0xc0?}, 0x0?)
	github.com/xtls/xray-core@v1.0.0/transport/internet/dialer.go:58 +0x1d0
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dial(0xc0003d0900, {0x1370d90?, 0xc0003db260?}, {{0x1370ff8, 0xc000391950}
, 0x1bb, 0x2})
	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:308 +0xb0b
github.com/xtls/xray-core/proxy/vmess/outbound.(*Handler).Process.func1()
	github.com/xtls/xray-core@v1.0.0/proxy/vmess/outbound/outbound.go:68 +0xa6
github.com/xtls/xray-core/common/retry.(*retryer).On(0xc000177c70, 0xc000177cd8)
github.com/xtls/xray-core@v1.0.0/common/retry/retry.go:27 +0xc6
github.com/xtls/xray-core/proxy/vmess/outbound.(*Handler).Process(0xc0003dade0, {0x1370d90, 0xc0003db260}, 0xc000181f40, {0x1368ef8, 0xc0003d0900})
	github.com/xtls/xray-core@v1.0.0/proxy/vmess/outbound/outbound.go:66
+0x1e5
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc0003d0900, {0x1370d90, 0xc0003db260}, 0xc000181f40
)
	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:238 +0x705
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(
0xc0003d63c0, {0x1370d90, 0xc0003db260}, 0xc000181f40, {{0x1370fc0, 0xc0003b5960}, 0x50,
0x2})
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:439 +0xbc2
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 26
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:234 +
0x48c

I use quic for network communication

**Comment by sausagenoods** [comment]
I have the same problem with Vmess + QUIC on Xray core.
