### ISSUE TITLE
Nekoray V 2.11 does not work properly, but version 2.9 works

### ISSUE THREAD

**Issue by GoatAL0** [MatsuriDayo/nekoray#298]
After upgrading to the latest version (2.11), I can't connect to any of my config VPN.
Debian 11 is my operating system.

Expected behavior: 
I want to connect to VPN config as before

Actual behavior:
It doesn't connect to any of my config.

log
[Warning] [3857827191] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > proxy/trojan: failed to transfer request payload > proxy/trojan: failed to write request header > tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

**Comment by bash99** [comment]
I also has this problem

some logs

```
V2Ray: 07a3c272 Neko: nekoray-2.11-2023-01-13
[2023-01-18 11:44:13] InitCore called  . moe.nekoray.pc:bg true
[2023-01-18 11:44:13] [Info] [tag=std] nekoray_core grpc server listening at 127.0.0.1:58011
>>>>>>>> 正在启动配置 [Trojan] 1910-trojan
[2023-01-18 11:44:14] [Warning] V2Ray 5.2.0 started
panic: interface conversion: interface {} is *utls.Config, not *tls.Config
goroutine 40 [running]:
github.com/v2fly/v2ray-core/v5/transport/internet/tls.ConfigFromStreamSettings(...)
	github.com/v2fly/v2ray-core/v5@v5.0.0/transport/internet/tls/config.go:286
github.com/v2fly/v2ray-core/v5/transport/internet/grpc.dialgRPC({0x110a4c0, 0xc00055c300}, {{0x110bd78?, 0xc000911a20?}, 0x30?, 0x0?}, 0xc0006836d0)
	github.com/v2fly/v2ray-core/v5@v5.0.0/transport/internet/grpc/dial.go:50 +0x49b
github.com/v2fly/v2ray-core/v5/transport/internet/grpc.Dial({0x110a4c0, 0xc00055c300}, {{0x110bd78?, 0xc000911a20?}, 0x38?, 0x0?}, 0x28090a20598?)
	github.com/v2fly/v2ray-core/v5@v5.0.0/transport/internet/grpc/dial.go:29 +0x1b8
github.com/v2fly/v2ray-core/v5/transport/internet.Dial({0x110a4c0, 0xc00055c300}, {{0x110bd78?, 0xc000911a20?}, 0x79ac?, 0x0?}, 0x3?)
	github.com/v2fly/v2ray-core/v5@v5.0.0/transport/internet/dialer.go:56 +0x21e
github.com/v2fly/v2ray-core/v5/app/proxyman/outbound.(*Handler).Dial(0xc00082e180, {0x110a4c0?, 0xc00055c300?}, {{0x110bd78?, 0xc000911a20?}, 0x0?, 0x0?}
)
	github.com/v2fly/v2ray-core/v5@v5.0.0/app/proxyman/outbound/handler.go:343 +0xe4f
github.com/v2fly/v2ray-core/v5/proxy/trojan.(*Client).Process.func1()
	github.com/v2fly/v2ray-core/v5@v5.0.0/proxy/trojan/client.go:63 +0xa2
github.com/v2fly/v2ray-core/v5/common/retry.(*retryer).On(0xc000d33b50, 0xc000d33bb8)
	github.com/v2fly/v2ray-core/v5@v5.0.0/common/retry/retry.go:27 +0xcf
github.com/v2fly/v2ray-core/v5/proxy/trojan.(*Client).Process(0xc000366e20, {0x110a4c0, 0xc00055c300}, 0xc0000ec080, {0x11040f8, 0xc00082e180})
	github.com/v2fly/v2ray-core/v5@v5.0.0/proxy/trojan/client.go:61
+0x230
github.com/v2fly/v2ray-core/v5/app/proxyman/outbound.(*Handler).Dispatch(0xc00082e180, {0x110a4c0, 0xc00055c300}, 0xc000576040)
	github.com/v2fly/v2ray-core/v5@v5.0.0/app/proxyman/outbound/handler.go:241 +0xc34
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00078b180, {0x110a4c0, 0xc00055c300}, 0xc000576040, {{0x110bd78?, 0xc0000f4070?}, 0x0?, 0x0?})
	github.com/v2fly/v2ray-core/v5@v5.0.0/app/dispatcher/default.go:402 +0xbe3
github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
	github.com/v2fly/v2ray-core/v5@v5.0.0/app/dispatcher/default.go:242 +0x55a
created by github.com/v2fly/v2ray-core/v5/app/dispatcher.(*DefaultDispatcher).Dispatch
	github.com/v2fly/v2ray-core/v5@v5.0.0/app/dispatcher/default.go:222 +0x374
>>>>>>>> 正在停止配置 [Trojan] 1910-trojan
[Error] core exited, restarting.
[Error] gRPC: QNetworkReply::NetworkError code: -1919

```

**Comment by tdjnodj** [comment]
Well.I found that when I use uTLS: chrome_102,I got the same problem.

**Comment by hossein-mohseni** [comment]
Same problem in nekoray and Matsuri in Android

**Comment by hossein-mohseni** [comment]
> https://www.v2fly.org/en_US/v5/config/stream.html#utls
> 
> GRPC is not supported yet.

how that is possible if it's working perfect in V2.9?!
but not working in new version!!

**Comment by tdjnodj** [comment]
> > https://www.v2fly.org/en_US/v5/config/stream.html#utls
> > GRPC is not supported yet.
> 
> how that is possible if it's working perfect in V2.9?! but not working in new version!!

In version 2.9, it's not really enabled, those options only apply to the sing-box.

**Comment by bash99** [comment]
Trojan over grpc still not work on 2.14, plain trojan also has so many problems, I can not believe it need to resolve my server ip every time.

naive plugin also got many errors.

I'll stick 2.9 for a while.
