### ISSUE TITLE
3.18 error 

### ISSUE THREAD

**Issue by papampi** [MatsuriDayo/nekoray#825]
Updated to 3.18 and getting this error on ubuntu 22.04:

```2023/08/24 08:27:53 [Warning] core: Xray 1.8.3 started
2023/08/24 08:27:53 tcp:127.0.0.1:48574 accepted tcp:94.140.14.15:443 [socks-in -> proxy]
panic: reflect: call of reflect.Value.Elem on struct Value
goroutine 53 [running]:
reflect.Value.Elem({0x10e47c0?, 0x1c234a0?, 0x1c234a0?})
	reflect/value.go:1271 +0x193
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10e47c0, 0x1c234a0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:34 +0xd9
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc000398840
?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc001b4e3c0?})
github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc0003fd130?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0001f8cf0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0001f93b0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0001f9920?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0000c4150?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc0003fd1d0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys
({0x10758c0, 0xc0000c4390?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys(
{0x10758c0, 0xc0000c43c0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.CorePtrFromContext({0x1366650
?, 0xc0000c43c0})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:77 +0x45
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000173580, {0x1366650, 0xc0000c43c0},
0xc002868620)
	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:175 +0x12e
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0000beea0
, {0x1366650, 0xc0000c43c0}, 0xc002868620, {{0x1366880, 0xc002864070}, 0x1bb, 0x2})
github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:490 +0xbc2
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:323 +0x4bd
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 52
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:304 +0x3c5
[Error] Core exited, restarting.
>>>>>>>> Stopping profile [VLESS] xxxxxxxxxxxxxxxxxxx
Xray: 02b41a7 NekoRay: nekoray-3.18-2023-08-24
2023/08/24 08:27:54 nekoray_core grpc server listening at 127.0.0.1:41855
>>>>>>>> Starting profile [VLESS] xxxxxxxxxxxxxxxxxxx
2023/08/24 08:27:55 [Warning] core: Xray 1.8.3 started
2023/08/24 08:27:55 tcp:127.0.0.1:48736 accepted tcp:94.140.14.15:443 [socks-in -> proxy]
panic: reflect: call of reflect.Value.Elem on struct Value
goroutine 51 [running]:
reflect.Value.Elem({0x10e47c0?, 0x1c234a0?, 0x1c234a0?})
	reflect/value.go:1271 +0x193
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10e47c0, 0x1c234a0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:34 +0xd9
github.com/xtls/xray-core/nekoutils.getCtxKeys(
{0x10758c0, 0xc00016a7b0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0
, 0xc0026f34d0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc0000a4230?})
github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0003803f0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:
50 +0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc000380450?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50
+0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc000380480?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50
+0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0003809c0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +
0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc0000a44b0?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50
+0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc000380a80?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +
0x4d1
github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc000380c00?})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +
0x4d1
github.com/xtls/xray-core/nekoutils.CorePtrFromContext({0x1366650?, 0xc000380c00})
	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:77 +0x45
github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000273580
, {0x1366650, 0xc000380c00}, 0xc0029b0100)
	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:175 +0x12e
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc0001d2c60, {0x1366650, 0xc000380c00}, 0xc0029b0100, {{
0x1366880, 0xc0003842b0}, 0x1bb, 0x2})
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:490 +0xbc2
github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:323 +0x4bd
created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 50
github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:304 +0x3c5
[Error] Core exits too frequently, stop automatic restart this profile.
>>>>>>>> Stopping profile [VLESS] xxxxxxxxxxxxxxxxxxx```

**Comment by Zhopeful88** [comment]
> Updated to 3.18 and getting this error on ubuntu 22.04:
> 
> ```
> Xray: 02b41a7 NekoRay: nekoray-3.18-2023-08-24
> 2023/08/24 08:37:24 nekoray_core grpc server listening at 127.0.0.1:44889
> >>>>>>>> Starting profile [VLESS] xxxxxxxxxxxxxxxxxxx
> 2023/08/24 08:37:32 [Warning] core: Xray 1.8.3 started
> 2023/08/24 08:37:33 tcp:127.0.0.1:47744 accepted tcp:138.199.10.27:501 [socks-in -> proxy]
> panic: reflect: call of reflect.Value.Elem on struct Value
> goroutine 41 [running]:
> reflect.Value.Elem({0x10e47c0?, 0x1c234a0?, 0x1c234a0?})
> 	reflect/value.go:1271 +0x193
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10e47c0, 0x1c234a0?
> })
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:34 +0xd9
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0002594d0?}
> )
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc00287fe30?})
> github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc0004371d0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50
> +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc00010cba0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50
> +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc00010cc00?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc00010cc60?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc00010d0e0
> ?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc000437270?}
> )
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc00010d1a0?
> })
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc00010d1d0?
> })
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.CorePtrFromContext({0x1366650?, 0xc00010d1d0})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:77 +0x45
> github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc0002b3580, {0x1366650, 0xc00010d1d0}, 0xc001f62600
> )
> 	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:175 +0x12e
> github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc00007de00
> , {0x1366650, 0xc00010d1d0}, 0xc001f62600, {{0x13668b8, 0xc000cb3d98}, 0x1f5, 0x2
> })
> 	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:490 +0xbc2
> github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
> 	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:
> 323 +0x4bd
> created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 40
> 	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:304 +0x3c5
> [Error] Core exited, restarting.
> >>>>>>>> Stopping profile [VLESS] xxxxxxxxxxxxxxxxxxx
> Xray: 02b41a7 NekoRay: nekoray-3.18-2023-08-24
> 2023/08/24 08:37:34 nekoray_core grpc server listening at 127.0.0.1:44889
> >>>>>>>> Starting profile [VLESS] xxxxxxxxxxxxxxxxxxx
> 2023/08/24 08:37:35 [Warning] core: Xray 1.8.3 started
> panic: reflect: call of reflect.Value.Elem on struct Value
> goroutine 12 [running]:
> reflect.Value.Elem({0x10e47c0?, 0x1c234a0?, 0x1c234a0?})
> 	reflect/value.go:1271 +0x193
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10e47c0, 0x1c234a0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:34 +0xd9
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc0000af1d0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc002c949f0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc0004111d0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0
> , 0xc002c958c0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc002c958f0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc002c95920?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc002c95ad0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10c7ec0, 0xc000411270?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc002c95b90?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.getCtxKeys({0x10758c0, 0xc002c95bc0?})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:50 +0x4d1
> github.com/xtls/xray-core/nekoutils.CorePtrFromContext({0x1366650?, 0xc002c95bc0})
> 	github.com/xtls/xray-core@v1.0.0/nekoutils/nekoutils.go:77 +0x45
> github.com/xtls/xray-core/app/proxyman/outbound.(*Handler).Dispatch(0xc000177580, {0x1366650, 0xc002c95bc0}, 0xc001f54fa0)
> 	github.com/xtls/xray-core@v1.0.0/app/proxyman/outbound/handler.go:175 +0x12e
> github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).routedDispatch(0xc000343da0, {0x1366650, 0xc002c95bc0}, 0xc001f54fa0, {{0x1366880, 0xc0003f82d0}, 0x1bb, 0x2})
> 	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:490 +0xbc2
> github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch.func1()
> 	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:323 +0x4bd
> created by github.com/xtls/xray-core/app/dispatcher.(*DefaultDispatcher).Dispatch in goroutine 11
> 	github.com/xtls/xray-core@v1.0.0/app/dispatcher/default.go:304 +0x3c5
> [Error] Core exits too frequently, stop automatic restart this profile.
> >>>>>>>> Stopping profile [VLESS] xxxxxxxxxxxxxxxxxxx```
> ```

Yes，can't not open it

**Comment by Zhopeful88** [comment]
一直提示core 退出太频繁，太频繁

**Comment by irtux** [comment]
Hi, Same problem with xray-core, switched  to 3.17 and works fine.

**Comment by davoola** [comment]
3.18版的问题，回退到3.17即可。
或者在3.18把核心更换成sing-box也可

**Comment by papampi** [comment]
> 3.18版的问题，回退到3.17即可。 或者在3.18把核心更换成sing-box也可

3.18 is pre-release, so we are just reporting issue to get fixed for release point

**Comment by Zhopeful88** [comment]
> Seems to cause some bugs while Xray-core upgrading.
> 
> Download and replace these Core files.
> 
> https://gofile.io/d/P7C3wl

有个文件没有后缀，单独替换后打开报错

**Comment by xchacha20-ietf-poly1305** [comment]
> > Seems to cause some bugs while Xray-core upgrading.
> > Download and replace these Core files.
> > https://gofile.io/d/P7C3wl
> 
> 有个文件没有后缀，单独替换后打开报错

您可能想使用 .exe 作为必须的后缀

**Comment by Zhopeful88** [comment]
> > > Seems to cause some bugs while Xray-core upgrading.
> > > Download and replace these Core files.
> > > https://gofile.io/d/P7C3wl
> > 
> > 
> > 有个文件没有后缀，单独替换后打开报错
> 
> 您可能想使用 .exe 作为必须的后缀

没看懂您这个回复是什么意思？我下载了两个文件直接替换，打开后直接报core 错误

**Comment by xchacha20-ietf-poly1305** [comment]
> > > > Seems to cause some bugs while Xray-core upgrading.
> > > > Download and replace these Core files.
> > > > https://gofile.io/d/P7C3wl
> > > 
> > > 
> > > 有个文件没有后缀，单独替换后打开报错
> > 
> > 
> > 您可能想使用 .exe 作为必须的后缀
> 
> 没看懂您这个回复是什么意思？我下载了两个文件直接替换，打开后直接报core 错误

如果您使用 windows，则必须使用 .exe 后缀的。如果不能用，请自行编译。
