### ISSUE TITLE
BUG: Core 退出太频繁

### ISSUE THREAD

**Issue by fatfattea** [MatsuriDayo/nekoray#922]
## 描述问题
我的nekoray客户端选则sing-box核心，开启TUN模式，其他设置都是默认。
在使用cloudflare的workers搭建的vless节点，进入youtube主页正常，但浏览视频就会在日志区出现“Core 退出，正在重新启动”，重新启动几次就提示Core 退出太频繁。
奇怪的是浏览其他视频网站不会出现这个问题，或者换其他节点也没有这个问题。

## 日志
panic: Decrementing non-positive ref count 0xc0000f2a00, owned by stack.PacketBuffer
goroutine 8077 [running]:
github.com/sagernet/gvisor/pkg/tcpip/stack.(*packetBufferRefs).DecRef(0xc0000f2a00, 0x0?)
	github.com/sagernet/gvisor@v0.0.0-20230627031050-1ab0276e0dd2/pkg/tcpip/stack/packet_buffer_refs.go:125 +0x10c
github.com/sagernet/gvisor/pkg/tcpip/stack.(*PacketBuffer).DecRef(...)
	github.com/sagernet/gvisor@v0.0.0-20230627031050-1ab0276e0dd2/pkg/tcpip/stack/packet_buffer.go:202
github.com/sagernet/sing-tun.(*UDPBackWriter).Close(0xc0003c33c0)
	github.com/sagernet/sing-tun@v0.1.12-0.20230821065522-7545dc2d5641/stack_gvisor_udp.go:97 +0xa7
github.com/sagernet/sing/common/udpnat.(*conn).Close(0xc0003957a0)
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/udpnat/service.go:177 +0x7e
github.com/sagernet/sing/common/bufio.(*CachedPacketConn).Close(0xc0008d16c0?)
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/bufio/cache.go:219 +0x68
github.com/sagernet/sing/common.Close({0xc000c66ee0?, 0x2, 0xf7e6cc?})
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/cond.go:347 +0x82
github.com/sagernet/sing/common/canceler.(*TimerPacketConn).Close(0x0?)
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/canceler/packet.go:66 +0x5e
github.com/sagernet/sing/common.Close({0xc000c66fa0?, 0x2, 0x0?})
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/cond.go:347 +0x82
github.com/sagernet/sing/common/bufio.CopyPacketConnContextList.func3()
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/bufio/copy.go:406 +0x65
github.com/sagernet/sing/common/task.(*Group).RunContextList(0xc000b1d320, {0xc000c67248?, 0x2e4474517a8?, 0x2e4021f0108?})
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/task/task.go:97 +0x426
github.com/sagernet/sing/common/bufio.CopyPacketConnContextList({0xc000c67248, 0x1, 0x1}, {0x2e447560460?, 0xc0004b1d58}, {0x2e447560510?, 0xc0000a0d10})
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/bufio/copy.go:409 +0x3a5
github.com/sagernet/sing/common/bufio.CopyPacketConn(...)
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/bufio/copy.go:394
github.com/sagernet/sing-box/outbound.NewPacketConnection({_, _}, {_, _}, {_, _}, {{0xc00030ebc8, 0x6}, {0x1dbc774, 0x3}, ...})
	github.com/sagernet/sing-box@v1.0.0/outbound/default.go:133 +0x69e
github.com/sagernet/sing-box/outbound.(*VLESS).NewPacketConnection(_,
{_, _}, {_, _}, {{0xc00030ebc8, 0x6}, {0x1dbc774, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box@v1.0.0/outbound/vless.go:126 +0x8b
github.com/sagernet/sing-box/route.(*Router).RoutePacketConnection(_, {_, _}, {_, _}, {{0xc00030ebc8, 0x6}, {0x1dbc774, 0x3}, 0x0, ...})
	github.com/sagernet/sing-box@v1.0.0/route/router.go:828 +0x17f4
github.com/sagernet/sing-box/inbound.(*Tun).NewPacketConnection(0xc000426200, {0x1f93378?, 0xc00053bef0?}, {0x1f98c80, 0xc0003957a0}, {{0x0, 0x0}, {{{0x0, 0xffffac130001}, 0xc000008030}, ...}, ...})
	github.com/sagernet/sing-box@v1.0.0/inbound/tun.go:223 +0x2f6
github.com/sagernet/sing/common/udpnat.(*Service[...]).NewContextPacket.func2()
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/udpnat/service.go:82 +0xc3
created by github.com/sagernet/sing/common/udpnat.(*Service[...]).NewContextPacket in goroutine 1968
	github.com/sagernet/sing@v0.2.10-0.20230912050851-1453c7c8c20d/common/udpnat/service.go:81 +0x38c
[Error] Core 退出，正在重新启动。
>>>>>>>> 正在停止配置 [VLESS] daweitianlong.64641153.workers.dev
sing-box-extra: 1.5.0-b8 NekoBox: nekoray-3.21-2023-09-12
2023/09/29 06:46:11 nekobox_core grpc server listening at 127.0.0.1:62446
>>>>>>>> 正在启动配置 [VLESS] daweitianlong.64641153.workers.dev
INFO[0000] router: updated default interface 以太网, index 8
INFO[0000] inbound/mixed[mixed-in]: tcp server started at 127.0.0.1:2080
<<<<<<<< 启动配置失败: [VLESS] daweitianlong.64641153.workers.dev
如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by Tresta16** [comment]
我这里是Fake DNS的原因，手头上两个服务器，一个关闭Fake DNS，TUN模式正常使用，一个关不关都不影响
